name: first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: make react build
        run: npm run build 